set(sources
    External/DearImGui/Source/imgui.cpp
    External/DearImGui/Source/imgui_demo.cpp
    External/DearImGui/Source/imgui_draw.cpp
    External/DearImGui/Source/imgui_widgets.cpp
    External/DearImGui/Source/imgui_tables.cpp
    External/DearImGui/Source/imgui_impl_opengl3.cpp
    External/DearImGui/Source/imgui_impl_glfw.cpp
    Source/PassDepot.cpp
    Source/PDWindow.cpp
    Source/PDGUI.cpp
    Source/PDDatabase.cpp
    Source/PDSecurity.cpp
)

set(exe_sources
		Source/main.cpp
		${sources}
)
